### PR TITLE
[commhistory-daemon] Let voicecall log calls.

### PR DESCRIPTION
**Pull request by dcaliste**
Simply handle notifications for missed calls,
and let the voicecall handle the logging.

@pvuorela, this is a draft to avoid duplicated entries when used in conjunction with sailfishos/voicecall#18. I've still not yet removed the unused streamchannellistener files. I'm keeping them at the moment for comparison. If you agree with the approach, I'll do a better PR here.

I'm a bit uneased that removing this streamchannellistener will loose the call video support though. Voicecall has no support for video calls and I cannot see any in the forseeable future since common video call solution use a closed ecosystem. So maybe it's not that important.

I'm wondering also about the conference call support. I cannot test it, and I've no idea how this is handle currently. Looking at the code, I think I've done something similar to the streamchannellistener, but not sure.

### CODE REVIEW

**Review by pvuorela — COMMENTED** [review]
Seems mostly nice and simple here. The most curious detail being the showNotification(). A bit pondering whether voicecall should also take care of that, but I can understand that just doing it here is the simpler way to get forward.

Can't make comment there, but for another detail wonder if Logger ctor still needs streamedMediaCall filter.

For what it could go wrong is maybe restoring some backup with a call log type of case, but commhistory-tool seems doing only addEvents() so maybe that's fine.

> I'm a bit uneased that removing this streamchannellistener will loose the call video support though. Voicecall has no support for video calls and I cannot see any in the forseeable future since common video call solution use a closed ecosystem. So maybe it's not that important.

I'm not sure is there much to lose here. Video calls would require an application to handle them and if there would be some, they could just do the log entries themselves.

> I'm wondering also about the conference call support. I cannot test it, and I've no idea how this is handle currently. Looking at the code, I think I've done something similar to the streamchannellistener, but not sure.

That's  indeed a bit hazy direction. Already halfway not working, at least volte side missing i think. Maybe log items are smaller problem there.

**Comment by dcaliste** [comment]
> Can't make comment there, but for another detail wonder if Logger ctor still needs streamedMediaCall filter.

Good catch. I've removed it.

**Comment by dcaliste** [comment]
> The most curious detail being the showNotification(). A bit pondering whether voicecall should also take care of that, but I can understand that just doing it here is the simpler way to get forward.

Indeed. There is already a notification manager here, that handle notifications, restoring them on device restart… That's why I've left the notification here, since all the management logic already exists. It avoid also to add a dependency of notification for the voicecall plugin. Not a big deal, but since there's already code for it here…

> Video calls would require an application to handle them and if there would be some, they could just do the log entries themselves.

Yes, that's my line of thoughts also. Just in case, I created a branch in dcaliste/voicecall called `video` where I've migrated the code to expose the video status. I know it's called _voice_call, but it was just to keep the code somewhere visible (even if it's still visible through the git history in commhistory-daemon).

I've added a commit that completely removes any mention to streamed media channels from Telepathy.

**Review by pvuorela — APPROVED** [review]
I'll just approve this already. Time to remove the draft status? No reasons not to merge? 

Created task JB#62417 for moving the logging. You can use that on commit, but I can also just annotate the tag.

Might consider squashing the commits?

**Comment by dcaliste** [comment]
Ok, let's go. I've removed the draft status, squashed the commits and added the JB number. Thanks for the review.

**Pull request merged**
